spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/spring3?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: welcome123
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080